// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package events

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID              string
	Source          string
	Type            string
	Specversion     string
	Datacontenttype pgtype.Text
	Data            []byte
	Time            pgtype.Timestamptz
	Subject         pgtype.Text
}
